<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\DanielRodrigo.PruebaNET.Application\DanielRodrigo.PruebaNET.Application.csproj" />
    <ProjectReference Include="..\..\src\DanielRodrigo.PruebaNET.Infrastructure\DanielRodrigo.PruebaNET.Infrastructure.csproj" />
    <ProjectReference Include="..\DanielRodrigo.PruebaNET.TestSupport\DanielRodrigo.PruebaNET.TestSupport.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.Testing" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
